[package]
name = "ns16650"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rille_user = { path = "../rille_user" }
rille = { path = "../../rille" }
rt = { path = "../rt" }