[package]
name = "procsvr"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rille = { path = "../../rille" }
rille_user = { path = "../rille_user" }