[package]
name = "rille"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"

[dependencies.num_enum]
version = "0.7.0"
default-features = false

[features]
kernel = []